### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by webserveis** [shchurov/HorizontalWheelView#1]
Great library!

In the next update I would like to be supported, for all values (int, floats, time, date etc..)

 - Set min value
 - Set max value
 - Set start value

**Comment by shchurov** [comment]
Hi @webserveis. Thanks for your feedback!

In my opinion supporting all those types would bloat API. However, I agree that there should be some more general type that can be easily converted to a required one. Most probably it's float (-1..1).

**Comment by shchurov** [comment]
Complete turn fraction support added in https://github.com/shchurov/HorizontalWheelView/commit/c1ee3cd824c015dd381f701ff54d2dc6f8495d68

**Comment by HBiSoft** [comment]
I agree that it would've been nice to have the option to set the minimum, maximum and current value. Currently, you are restricting the library to rotational implementations only. By adding this methods, the library can be used as a `SeekBar` and opens the door to so many implementations.
