### ISSUE TITLE
How can I stop the touch?

### ISSUE THREAD

**Issue by JungYongWook** [shchurov/HorizontalWheelView#11]
Hello,
I use the Android studio,
I added compile
`compile 'com.github.shchurov:horizontalwheelview:0.9.5'`
to the build.gradle file.

How can I stop the touch?

**Comment by shchurov** [comment]
Hi @JungYongWook!
Sorry, I didn't understand. Do you want to make it so it will ignore any user touch?

**Comment by JungYongWook** [comment]
Yes that's what I want !

**Comment by JungYongWook** [comment]
I've fixed this issue. Thank good library!
