### ISSUE TITLE
Mark gap space between marks

### ISSUE THREAD

**Issue by bhavinsetubridge** [shchurov/HorizontalWheelView#13]
Is there any solution to find space between visible marks. 

when number of marks count is less than 40 ,the space between mark automatically increase.

can you please update regarding space between marks. 

`private void setupGaps(double step, double offset) {
        gaps[0] = (float) Math.sin(offset / 2);
        float sum = gaps[0];
        double angle = offset;
        int n = 1;
        while (angle + step <= Math.PI) {
            gaps[n] = (float) Math.sin(angle + step / 2);
            sum += gaps[n];
            angle += step;
            n++;
        }
        float lastGap = (float) Math.sin((Math.PI + angle) / 2);
        sum += lastGap;
        if (n != gaps.length) {
            gaps[gaps.length - 1] = -1;
        }
        float k = view.getWidth() / sum;
        for (int i = 0; i < gaps.length; i++) {
            if (gaps[i] != -1) {
                gaps[i] *= k;
            }
        }
    }`

**Comment by mikehodz** [comment]
Hi, @bhavinsetubridge 
Sorry, I don't fully understand what you mean. Maybe if you provide an example where you need this I will be able to help.
