### ISSUE TITLE
Support for Calendar?

### ISSUE THREAD

**Issue by vptcr** [shchurov/HorizontalWheelView#2]
Hi,
First, thank for this control. Just curious, are you planning to make a calendar week scroller with this?. Thanks.

**Comment by shchurov** [comment]
@vptcr Thanks for your feedback, I couldn't imagine how it should look like, do you have something on your mind?
In general I'm not going to implement all possible types of data (date, time, temperature etc.) but I have some plans on making it more customizable.

**Comment by vptcr** [comment]
I was thinking something like a Horizontal Week View scroller.

**Comment by shchurov** [comment]
@vptcr so there would be SUN MON TUE WED THU FRI SAT instead of marks?

The problem is that it requires a different mechanic, e.g. you can't select something between 2 days

**Comment by vptcr** [comment]
Yes. The week strip cannot take in in-between values.

**Comment by shchurov** [comment]
@vptcr It requires different behaviour in terms of code, in my opinion it would be easier to create such view from scratch
