### ISSUE TITLE
its not flinging

### ISSUE THREAD

**Issue by klodianpepkolaj** [shchurov/HorizontalWheelView#3]
scroll not fling

**Comment by shchurov** [comment]
Hi @klodianpepkolaj , thanks for your feedback. Could you describe the issue in more details (device model, steps to reproduce etc.)
As you can see on the demo-gif fling works under normal circumstances.

**Comment by klodianpepkolaj** [comment]
@shchurov tried already on 3 different devices with different SDK versions , everything works fine except flinging

**Comment by shchurov** [comment]
@klodianpepkolaj  I can't come up with anything that could cause this issue. Works just fine for me. Could you try to debug it? The class name is `TouchHandler`, it's pretty straightforward.

**Comment by klodianpepkolaj** [comment]
@shchurov yes thats what i am trying to do, but not able to find the error, API 19, 21,22, already tried

**Comment by klodianpepkolaj** [comment]
@shchurov made there is an error in the code you have commited, please update the code here in github

**Comment by shchurov** [comment]
@klodianpepkolaj It's the latest version, may I ask you to make a video of that issue?

**Comment by klodianpepkolaj** [comment]
@shchurov the issue was, when on developer options, and animation scale 0x, it doesnt work, but I found another solution for this that the fling works even when developer options are on. thanks

**Comment by shchurov** [comment]
@klodianpepkolaj great, I just thought yesterday that it could be related to those animation settings. Glad that you resolved it.
