### ISSUE TITLE
Set max,min,start

### ISSUE THREAD

**Issue by canberkcakmak** [shchurov/HorizontalWheelView#4]
Hi, is there any way to set min, max and start value?

**Comment by shchurov** [comment]
Hi @canberkcakmak,
There're `setCompleteTurnFraction(double fraction)` and `getCompleteTurnFraction()`. It changes in range (-1, 1). So all you need is to figure out the function that converts (-1, 1) -> (min, max). 

PS I have an idea how to make it even easier, I'll write an update here when finish

**Comment by shchurov** [comment]
@canberkcakmak 
I've made an update, there's a new method `setOnlyPositiveValues()` in the version `0.9.4`. If set to true `getCompleteTurnFraction()` will return values only in range (0,1).
So your conversion function will look like this:
`double converted =  min + (max - min) * value;`
And to set start value:
`view.setCompleteTurnFraction((startValue - min) / (max - min));`

**Comment by alexeyvasilyev** [comment]
The solution does not work in my case.

I want to make a component for selecting video playback speed.
Speed can vary from 0.1x to 4x with 1x by default.
With your approach when the user selects 4x and continue to rotate the wheel he will get 0.1x speed. Which is not good.

I want to say min and max value for the view to be used only for the fraction of the wheel.

**Comment by shchurov** [comment]
Hi @alexeyvasilyev ,
Do you want the wheel to be locked for further rotation if it has already reached min / max value?

**Comment by alexeyvasilyev** [comment]
Yes, wheel should be locked when min/max value reached.

**Comment by canberkcakmak** [comment]
yes. I think this update makes your library better.

**Comment by shchurov** [comment]
setEndLock(boolean lock) added in ed69fe2f7ab54964cdf273efc2d2a8f4f8c51e8e 
It will be included in the next release

**Comment by shchurov** [comment]
`setSnapToMarks(boolean snapToMarks)` added in ef3198e78613d89b86bd5201db9675d81b4fe7a4
It will be included in the next release

**Comment by shchurov** [comment]
@alexeyvasilyev, @canberkcakmak , **0.9.5** is released, thanks!

**Comment by canberkcakmak** [comment]
Thanks too. Have a nice day

**Comment by alexeyvasilyev** [comment]
Thanks!

**Comment by alexeyvasilyev** [comment]
Still no way to specify min and max values to be used.
It is not possible to say for 360 degrees wheel to use only part of the wheel from let's say 100 degrees to 200 degrees.

And also it is not clear what setCompleteTurnFraction() function is doing. I would suggest to add `setMin`, `setMax`, `setStart` methods.

**Comment by shchurov** [comment]
@alexeyvasilyev, could you provide a use case for that feature? Why do you need to use only a part of the wheel?

`setCompleteTurnFraction()` works in the same way as `setDegreesAngle()` or `setRadiansAngle()` but you pass there values in range [-1, 1] i.e. 0° = 0, 180° = 0.5f, -360° = -1f
