### ISSUE TITLE
Make showActiveRange(boolean) method

### ISSUE THREAD

**Issue by alexeyvasilyev** [shchurov/HorizontalWheelView#5]
You can set showActiveRange only via xml at the moment.

**Comment by shchurov** [comment]
Hi @alexeyvasilyev ,
Could you provide an example where you need that feature? 
I was thinking about duplicating some of the xml-attributes in the code. But I can't imagine any usecase for that particular attribute.

**Comment by alexeyvasilyev** [comment]
I guess it is general a good idea to duplicate xml attributes as methods.

**Comment by shchurov** [comment]
@alexeyvasilyev 
The problem that changing values on the fly brings a lot of logic to the code that must be supported for all future releases. I would wait for api to become more stable before doing that. Because atm api is based on my assumptions not the real use cases.

**Comment by shchurov** [comment]
`setShowActiveRange(boolean show)` added in 228752e0eadf733ff7ecf33ba4d5d2e251cc07ca
It will be included in the next release

**Comment by shchurov** [comment]
@alexeyvasilyev, **0.9.5** is released, thanks!
