### ISSUE TITLE
Allow deterministic values

### ISSUE THREAD

**Issue by alexeyvasilyev** [shchurov/HorizontalWheelView#6]
At the moment all methods return float values.

I want to have only a couple values (5) in the wheel. To do that two additional methods (beside setMin/setMax) should be added.

Add a method setIntegerValues(boolean) which will force view to return only int values.
Add a method setMarkInterval(int) to say when exactly marks should be drawn.

Then I can say in the code:
view.setMin(0);
view.setMax(4);
view.setIntegerValues(true);
view.setMarkInterval(1);

**Comment by shchurov** [comment]
Hi @alexeyvasilyev,
Atm it has `setMaxVisibleMarks` attribute though it's not accurate if you want to set the total number of marks. But I think that could be a nice feature, I will try to figure out what's the best way to implement it. Regarding `setIntegerValues`, do you want the wheel to snap to the marks?

**Comment by alexeyvasilyev** [comment]
Yes, it should snap to the marks.

PS. Again it has maxVisibleMarks xml attribute, but not setMaxVisibleMarks method.

**Comment by shchurov** [comment]
@alexeyvasilyev those are reasonable features, I will add them

**Comment by shchurov** [comment]
e04242a5bfe395c846fbebd340da9775ecd2a66f `maxVisibleMarks` changed to `marksCount`, I also added method `setMarksCount(int count)`.
It will be included in the next release

**Comment by shchurov** [comment]
@alexeyvasilyev, **0.9.5** is released, thanks!
