### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by JungYongWook** [shchurov/HorizontalWheelView#9]
I'd like to use it in the ongoing project.
But I don't know how to use it.
Can you explain it?

Build gradle file is created.
I just want the wheel part.All the images of the rocket have been removed.

Touch also disabled.
But I don't know how to put it on my project.

**Comment by shchurov** [comment]
Hi @JungYongWook
In the simplest case you need to add this to your root `build.gradle`:
```
allprojects {
 repositories {
    jcenter()
    maven { url "https://jitpack.io" }
 }
}
```

this to the dependencies list in the app `build.gradle`:
```
compile 'com.github.shchurov:horizontalwheelview:0.9.5'
```

and this to your xml layout:
```
<com.github.shchurov.horizontalwheelview.HorizontalWheelView
            android:id="@+id/horizontalWheelView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>
```
